import { request, upload } from '@core/http.js'

// the site's own calls; the platform's are in @core/api.js
export const getStudentGame = (nick) => request(`/api/students/${nick}/game`)
export const getZones = () => request('/api/zones')
export const getGames = () => request('/api/games')
export const getTasks = () => request('/api/tasks')
export const postGame = (data) => request('/api/games', 'POST', data)
export const putGame = (id, data) => request(`/api/games/${id}`, 'PUT', data)
export const postTask = (data) => request('/api/tasks', 'POST', data)
export const putTask = (id, data) => request(`/api/tasks/${id}`, 'PUT', data)
export const getCardHistory = (kind, slug) => request(`/api/catalog/history/${kind}${slug ? `?slug=${slug}` : ''}`)
export const revertCard = (kind, id) => request(`/api/catalog/history/${kind}/${id}/revert`, 'POST')
export const getMyGame = () => request('/api/my/game')
export const postMyGame = (data) => request('/api/my/game', 'POST', data)
export const putMyGame = (data) => request('/api/my/game', 'PUT', data)
export const postPart = (data) => request('/api/my/game/parts', 'POST', data)
export const putPart = (id, data) => request(`/api/my/game/parts/${id}`, 'PUT', data)
export const deletePart = (id) => request(`/api/my/game/parts/${id}`, 'DELETE')
export const uploadShot = (id, file) => upload(`/api/my/game/parts/${id}/screenshot`, file)
export const deleteShot = (id, name) => request(`/api/my/game/parts/${id}/screenshot/${name}`, 'DELETE')
export const postClaim = (data) => request('/api/my/claims', 'POST', data)
export const putClaim = (id, data) => request(`/api/my/claims/${id}`, 'PUT', data)
export const deleteClaim = (id) => request(`/api/my/claims/${id}`, 'DELETE')
export const postRule = (data) => request('/api/my/game/rules', 'POST', data)
export const putRule = (id, data) => request(`/api/my/game/rules/${id}`, 'PUT', data)
export const deleteRule = (id) => request(`/api/my/game/rules/${id}`, 'DELETE')
export const getRefs = () => request('/api/refs')
export const postRef = (data) => request('/api/refs', 'POST', data)
export const putRef = (id, data) => request(`/api/refs/${id}`, 'PUT', data)
export const deleteRef = (id) => request(`/api/refs/${id}`, 'DELETE')
