import { query, request } from './http.js'

export const getMe = () => request('/api/me')
export const putProfile = (data) => request('/api/profile', 'PUT', data)
export const unlinkTelegram = () => request('/api/me/telegram', 'DELETE')
export const postView = (path) => request('/api/me/view', 'POST', { path })
export const postError = (data) => request('/api/errors', 'POST', data)
export const viewAs = (nick) => request(`/api/me/as/${nick}`, 'POST')
export const stopViewAs = () => request('/api/me/as', 'DELETE')
export const getStudents = () => request('/api/students')
export const getStudent = (nick) => request(`/api/students/${nick}`)
export const putStudent = (nick, data) => request(`/api/students/${nick}`, 'PUT', data)
export const importStudents = (text) => request('/api/students/import', 'POST', { text })
export const getActivity = (params) => request(`/api/activity${query(params)}`)
export const getActivityPeople = (params) => request(`/api/activity/people${query(params)}`)
export const getGuide = () => request('/api/guide')
export const getGuidePage = (slug) => request(`/api/guide/${slug}`)
export const putGuidePage = (slug, data) => request(`/api/guide/${slug}`, 'PUT', data)
export const getGuideHistory = (slug) => request(`/api/guide/history${slug ? `?slug=${slug}` : ''}`)
export const publishChange = (line) => request('/api/guide/changes/publish', 'POST', { line })
