import { query, request } from './http.js'

export const getMe = () => request('/api/me')
export const putProfile = (data) => request('/api/profile', 'PUT', data)
export const unlinkTelegram = () => request('/api/me/telegram', 'DELETE')
export const postView = (path) => request('/api/me/view', 'POST', { path })
export const postError = (data) => request('/api/errors', 'POST', data)
export const viewAs = (nick) => request(`/api/me/as/${nick}`, 'POST')
export const stopViewAs = () => request('/api/me/as', 'DELETE')
export const getStudents = () => request('/api/students')
export const getStudent = (nick) => request(`/api/students/${nick}`)
export const putStudent = (nick, data) => request(`/api/students/${nick}`, 'PUT', data)
export const importStudents = (text) => request('/api/students/import', 'POST', { text })
export const getActivity = (params) => request(`/api/activity${query(params)}`)
export const getActivityPeople = (params) => request(`/api/activity/people${query(params)}`)
export const getGuide = () => request('/api/guide')
export const getGuidePage = (slug) => request(`/api/guide/${slug}`)
export const putGuidePage = (slug, data) => request(`/api/guide/${slug}`, 'PUT', data)
export const getGuideHistory = (slug) => request(`/api/guide/history${slug ? `?slug=${slug}` : ''}`)
export const publishChange = (line) => request('/api/guide/changes/publish', 'POST', { line })
export const getPolls = (params) => request(`/api/polls${query(params)}`)
export const getPoll = (id) => request(`/api/polls/${id}`)
export const postPoll = (data) => request('/api/polls', 'POST', data)
export const putPoll = (id, data) => request(`/api/polls/${id}`, 'PUT', data)
export const deletePoll = (id) => request(`/api/polls/${id}`, 'DELETE')
export const sendPoll = (id, data) => request(`/api/polls/${id}/send`, 'POST', data)
export const retrySend = (id, sid) => request(`/api/polls/${id}/sends/${sid}/retry`, 'POST')
export const closePoll = (id) => request(`/api/polls/${id}/close`, 'POST')
export const pollToTemplate = (id) => request(`/api/polls/${id}/template`, 'POST')
export const getPollMatrix = (params) => request(`/api/polls/matrix${query(params)}`)
export const getPollTemplates = () => request('/api/polls/templates')
export const postPollTemplate = (data) => request('/api/polls/templates', 'POST', data)
export const putPollTemplate = (id, data) => request(`/api/polls/templates/${id}`, 'PUT', data)
export const deletePollTemplate = (id) => request(`/api/polls/templates/${id}`, 'DELETE')
export const getPollChats = () => request('/api/polls/chats')
export const putPollChat = (id, data) => request(`/api/polls/chats/${id}`, 'PUT', data)
